name: Deploy Web CI

on:
  push:
    branches: ["main", "features/temp-cloudmos-maintain"]
  pull_request:
    branches: ["main", "features/temp-cloudmos-maintain"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Check for changes in deploy-web folder
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            deploy-web:
              - 'deploy-web/**'

      - name: Build the Docker image
        if: steps.filter.outputs.deploy-web == 'true'
        run: docker build ./deploy-web/
