name: Stats Web CI

on:
  push:
    branches: ["main", "collab-rebrand"]
  pull_request:
    branches: ["main", "collab-rebrand"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Check for changes in stats-web folder
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            stats-web:
              - 'stats-web/**'

      - name: Build the Docker image
        if: steps.filter.outputs.stats-web == 'true'
        run: docker build ./stats-web/
