name: Landing CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Check for changes
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            landing:
              - 'apps/landing/**'

      - name: Build the Docker image for LANDING
        if: steps.filter.outputs.landing == 'true'
        run: npm run dc:build -- landing
