name: Provider Proxy CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Check for changes
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            provider-proxy:
              - 'apps/provider-proxy/**'

      - name: Build the Docker image
        if: steps.filter.outputs.provider-proxy == 'true'
        run: docker build -f docker/Dockerfile.provider-proxy -t console-provider-proxy .
